const car = {
    lessThenFiveYears:{

        A:{
            "cc=1000":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            },
            "cc<1500":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            },
            "cc>1500":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            }
        },
        B:{
            "cc=1000":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            },
            "cc<1500":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            },
            "cc>1500":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            }
        },
    },
    lessThenTenYears:{
        A:{
            "cc=1000":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            },
            "cc<1500":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            },
            "cc>1500":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            }
        },
        B:{
            "cc=1000":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            },
            "cc<1500":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            },
            "cc>1500":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            }
        },
    },
    greaterThenTenYears:{
        A:{
            "cc=1000":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            },
            "cc<1500":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            },
            "cc>1500":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            }
        },
        B:{
            "cc=1000":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            },
            "cc<1500":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            },
            "cc>1500":{
                value:3.03,
                oneYearTp:3000,
                threeYearTp:0
            }
        }
    },
    accessoriespercent:4,
    noClaimBonus:4,
    PAunnamedPercent:0.05,
    premiumName:"School Bus"
}

module.exports={
    data:car
}