const car = {
    lessThenFiveYears:{
        A:{
            "cc<75":{
                value:1.708,
                oneYearTp:538,
                fiveYearTp:2901
            },
            "cc>75":{
                value:1.708,
                oneYearTp:714,
                fiveYearTp:3851
            },
            "cc<350":{
                value:1.793,
                oneYearTp:1366,
                fiveYearTp:7365
            },
            "cc>350":{
                value:1.879,
                oneYearTp:2804,
                fiveYearTp:15117
            }
        },
        B:{
            "cc<75":{
                value:1.676,
                oneYearTp:538,
                fiveYearTp:2901
            },
            "cc>75":{
                value:1.676,
                oneYearTp:714,
                fiveYearTp:3851
            },
            "cc<350":{
                value:1.760,
                oneYearTp:1366,
                fiveYearTp:7365
            },
            "cc>350":{
                value:1.844,
                oneYearTp:2804,
                fiveYearTp:15117
            }
        },
  
    },
    lessThenTenYears:{    
        A:{
            "cc<75":{
                value:1.793,
                oneYearTp:538,
                fiveYearTp:2901
            },
            "cc>75":{
                value:1.793,
                oneYearTp:714,
                fiveYearTp:3851
            },
            "cc<350":{
                value:1.883,
                oneYearTp:1366,
                fiveYearTp:7365
            },
            "cc>350":{
                value:1.973,
                oneYearTp:2804,
                fiveYearTp:15117
            }
        },
        B:{
            "cc<75":{
                value:1.760,
                oneYearTp:538,
                fiveYearTp:2901
            },
            "cc>75":{
                value:1.760,
                oneYearTp:714,
                fiveYearTp:3851
            },
            "cc<350":{
                value:1.848,
                oneYearTp:1366,
                fiveYearTp:7365
            },
            "cc>350":{
                value:1.936,
                oneYearTp:2804,
                fiveYearTp:15117
            }
        },
        
    },
    greaterThenTenYears:{   
        A:{
            "cc<75":{
                value:1.836,
                oneYearTp:538,
                fiveYearTp:2901
            },
            "cc>75":{
                value:1.836,
                oneYearTp:714,
                fiveYearTp:3851
            },
            "cc<350":{
                value:1.928,
                oneYearTp:1366,
                fiveYearTp:7365
            },
            "cc>350":{
                value:2.020,
                oneYearTp:2804,
                fiveYearTp:15117
            }
        },
        B:{
            "cc<75":{
                value:1.802,
                oneYearTp:538,
                fiveYearTp:2901
            },
            "cc>75":{
                value:1.802,
                oneYearTp:714,
                fiveYearTp:3851
            },
            "cc<350":{
                value:1.892,
                oneYearTp:1366,
                fiveYearTp:7365
            },
            "cc>350":{
                value:1.982,
                oneYearTp:2804,
                fiveYearTp:15117
            }
        },
       
    },
    accessoriespercent:4,
    noClaimBonus:4,
    PAunnamedPercent:0.14,
    premiumName:"Two Wheeler Premium",
    tppd:-50
}

module.exports={
    data:car
}