import {
  GetCompany,
  PostCompany,
  DeleteCompany,
  UpdateCompany,
  FilterCompany,
} from "./CompanyService";
import {
  GetBranch,
  PostBranch,
  DeleteBranch,
  UpdateBranch,
  FilterBranch,
} from "./BranchService";
import {
  GetMasterCompany,
  PostMasterCompany,
  DeleteMasterCompany,
  UpdateMasterCompany,
  FilterMasterCompany,
} from "./MasterCompanyService";

// Changes by Arun
import {
  GetMasterReport,
  GetMasterReportExcelFormat,
  GetPaidReceivedReport,
  GetTDSReport,
  DeletePolicyReportData,
  UpdatePolicyReportData,
  GetPolicyChequeReport,
  GetBookingReport,
  GetDashboard,
} from "./ReportService";

import {
  GetBookingCode,
  PostBookingCode,
  DeleteBookingCode,
  UpdateBookingCode,
  FilterBookingCode,
} from "./BookingCodeService";
import {
  GetLinkBookingCode,
  PostLinkBookingCode,
  DeleteLinkBookingCode,
  UpdateLinkBookingCode,
  FilterLinkBookingCode,
} from "./LinkBookingCodeService";

import {
  GetPolicyPeriod,
  PostPolicyPeriod,
  DeletePolicyPeriod,
  UpdatePolicyPeriod,
  FilterPolicyPeriod,
} from "./PolicyPeriodService";

import {
  GetPolicyType,
  PostPolicyType,
  DeletePolicyType,
  UpdatePolicyType,
  FilterPolicyType,
} from "./PolicyTypeService";

import {
  GetProduct,
  PostProduct,
  DeleteProduct,
  UpdateProduct,
  FilterProduct,
} from "./ProductService";

import {
  PostUser,
  GetUser,
  GetLogin,
  UpdateUser,
  GetFileFromAWSS3BucketByKey,
  GetUserFindbyId,
  verifyMobileNumber,
  verifyEmailAddress,
} from "./UserService";

import {
  PostSearchPolicy,
  LoginPortalData,
  GetPolicyList,
  PostCreatePolicy,
  UpdatePolicyList,
  DeletePolicyList,
  FilterPolicyList,
  GetUserpayablePercentage,
  GetBranchpayablePercentage,
  GetReceivablePayablePercentage,
  GetPolicyFileById,
  AutoFillPolicyDetails,
  SaveComissionReceivableAmount,
  GetCommisionReceivableAmount,
  GetPolicyFindbyId,
  VerifyPolicyNumber,
  CreatePolicyMappingService,
  GetPolicyMapping,
  GetPolicyMappingByPolicyID,
  UpdatePolicyMapping,
  ReadPolicyFileByPolicyId
} from "./SearchPolicy";
import {
  GetCompanyLogin,
  PostCompanyLogin,
  DeleteCompanyLogin,
  UpdateCompanyLogin,
  FilterCompanyLogin,
  VerifyLoginId,
} from "./CompanyLoginService";

import {
  GetCompanyContact,
  PostCompanyContact,
  DeleteCompanyContact,
  UpdateCompanyContact,
  FilterCompanyContact,
} from "./CompanyContactService";

import {
  GetClient,
  PostClient,
  DeleteClient,
  UpdateClient,
} from "./ClientService";

import {
  GetSubProduct,
  PostSubProduct,
  DeleteSubProduct,
  UpdateSubProduct,
  FilterSubProduct,
} from "./SubProductService";
import { LoginService, RegisterService, GetOtp } from "./LoginService";
import {
  GetSubBookingCode,
  PostSubBookingCode,
  DeleteSubBookingCode,
  UpdateSubBookingCode,
  FilterSubBookingCode,
} from "./SubBookingCodeService";

import { GetRenewalData } from "./RenewalService";

import {
  GetFuelType,
  PostFuelType,
  DeleteFuelType,
  UpdateFuelType,
  FilterFuelType,
} from "./FuelTypeSerice";

// added by gokul..
import {
  GetVehicleMake,
  PostVehicleMake,
  UpdateVehicleMake,
  FilterVehicleMake,
  DeleteVehicleMake,
} from "./VehicleMakeService";
import {
  GetPayout,
  PostPayout,
  DeletePayout,
  UpdatePayout,
  FilterPayout,
} from "./PayoutService";

import {
  GetUserWallet,
  GetUserWalletByUserId,
  PaidWallet,
  GetBranchWallet,
  GetBranchWalletByUSerId,
  GetCompanyWallet,
  GetCompanyWalletBySubBookingCodeId,
  ReceivedWallet,
  GetBankDetailsByUserId,
} from "./WalletService";

import {
  GetRTO,
  PostRTO,
  GetCompanyRTO,
  GetCompanyRTOByID,
  UpdateCompanyRTO,
  DeleteRTO,
} from "./RTOService";
import {
  PostUserConfig,
  GetUserConfigByUserId,
  GetRTOLocationByCompanyID,
  DisableUserConfig,
  GetUserConfigById,
  UpdateUserConfig,
  DeleteUserConfig,
} from "./UserConfigService";
import {
  PostBranchConfig,
  GetBranchConfigByBranchManagerId,
  DisableBranchConfig,
  DeleteBranchConfig,
  GetBranchConfigById,
  UpdateBranchConfig,
} from "./BranchConfigService";
import {
  PostReceivableConfig,
  GetReceivableConfigByCompanyId,
  DisableReceivableConfig,
  UpdateReceivableConfig,
  DeleteReceivableConfigById,
  GetReceivableConfigById,
} from "./ReceivableConfigService";

import {
  GetVehicleDetails,
  PostVehicleDetails,
  DownloadPdf,
  GetQuoteQueryRecords,
} from "./MotorCalculationService";

export {
  GetCompany,
  PostCompany,
  DeleteCompany,
  UpdateCompany,
  FilterCompany,
  GetBranch,
  PostBranch,
  DeleteBranch,
  UpdateBranch,
  FilterBranch,
  GetMasterCompany,
  PostMasterCompany,
  DeleteMasterCompany,
  UpdateMasterCompany,
  FilterMasterCompany,
  GetBookingCode,
  PostBookingCode,
  DeleteBookingCode,
  UpdateBookingCode,
  GetLinkBookingCode,
  PostLinkBookingCode,
  DeleteLinkBookingCode,
  UpdateLinkBookingCode,
  FilterLinkBookingCode,
  FilterBookingCode,
  GetPolicyPeriod,
  PostPolicyPeriod,
  DeletePolicyPeriod,
  UpdatePolicyPeriod,
  FilterPolicyPeriod,
  GetPolicyType,
  PostPolicyType,
  DeletePolicyType,
  UpdatePolicyType,
  FilterPolicyType,
  GetProduct,
  PostProduct,
  DeleteProduct,
  UpdateProduct,
  FilterProduct,
  PostUser,
  UpdateUser,
  GetFileFromAWSS3BucketByKey,
  GetUserFindbyId,
  verifyMobileNumber,
  verifyEmailAddress,
  GetUser,
  GetLogin,
  PostSearchPolicy,
  LoginPortalData,
  GetPolicyMapping,
  GetPolicyMappingByPolicyID,
  CreatePolicyMappingService,
  FilterPolicyList,
  GetUserpayablePercentage,
  GetBranchpayablePercentage,
  GetReceivablePayablePercentage,
  GetPolicyFileById,
  UpdatePolicyMapping,
  ReadPolicyFileByPolicyId,
  AutoFillPolicyDetails,
  SaveComissionReceivableAmount,
  GetCommisionReceivableAmount,
  UpdatePolicyList,
  GetPolicyList,
  GetPolicyFindbyId,
  VerifyPolicyNumber,
  DeletePolicyList,
  PostCreatePolicy,
  GetCompanyLogin,
  PostCompanyLogin,
  DeleteCompanyLogin,
  UpdateCompanyLogin,
  FilterCompanyLogin,
  VerifyLoginId,
  GetCompanyContact,
  FilterCompanyContact,
  PostCompanyContact,
  DeleteCompanyContact,
  UpdateCompanyContact,
  GetClient,
  PostClient,
  DeleteClient,
  UpdateClient,
  GetSubProduct,
  PostSubProduct,
  DeleteSubProduct,
  UpdateSubProduct,
  FilterSubProduct,
  LoginService,
  RegisterService,
  GetOtp,
  GetSubBookingCode,
  PostSubBookingCode,
  DeleteSubBookingCode,
  UpdateSubBookingCode,
  FilterSubBookingCode,
  GetRenewalData,
  GetFuelType,
  PostFuelType,
  DeleteFuelType,
  UpdateFuelType,
  FilterFuelType,
  GetVehicleMake,
  PostVehicleMake,
  UpdateVehicleMake,
  FilterVehicleMake,
  DeleteVehicleMake,
  GetPayout,
  PostPayout,
  DeletePayout,
  UpdatePayout,
  FilterPayout,
  GetUserWallet,
  GetUserWalletByUserId,
  PaidWallet,
  GetBranchWallet,
  GetBranchWalletByUSerId,
  GetCompanyWallet,
  GetCompanyWalletBySubBookingCodeId,
  ReceivedWallet,
  GetBankDetailsByUserId,
  GetRTO,
  PostUserConfig,
  PostRTO,
  GetCompanyRTO,
  GetUserConfigByUserId,
  GetCompanyRTOByID,
  UpdateCompanyRTO,
  DeleteRTO,
  GetRTOLocationByCompanyID,
  DisableUserConfig,
  GetUserConfigById,
  DeleteUserConfig,
  PostBranchConfig,
  GetBranchConfigByBranchManagerId,
  DisableBranchConfig,
  GetBranchConfigById,
  UpdateBranchConfig,
  DeleteBranchConfig,
  PostReceivableConfig,
  GetReceivableConfigByCompanyId,
  DisableReceivableConfig,
  UpdateReceivableConfig,
  DeleteReceivableConfigById,
  GetReceivableConfigById,
  GetMasterReport,
  GetMasterReportExcelFormat,
  GetPaidReceivedReport,
  GetTDSReport,
  GetPolicyChequeReport,
  GetBookingReport,
  UpdateUserConfig,
  DeletePolicyReportData,
  GetDashboard,
  UpdatePolicyReportData,
  GetVehicleDetails,
  PostVehicleDetails,
  DownloadPdf,
  GetQuoteQueryRecords,
};
